spring:
  application:
    name: CadastroDeNinjas
  datasource:
    url: jdbc:h2:mem:ninjas
    driver-class-name: org.h2.Driver
    username: root
    password:
  h2:
    console:
      enabled: true